server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: shop_user
    password: shop_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      url: redis://localhost:6379
      timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 1
        batch.size: 16384
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      product-service:
        connectTimeout: 3000
        readTimeout: 3000
      payment-service:
        connectTimeout: 10000
        readTimeout: 10000

# Redisson Redis 분산락 설정
redisson:
  address: redis://localhost:6379
  password: 
  connection-pool-size: 64
  connection-minimum-idle-size: 24

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# 플래시 세일 특화 설정
flash-sale:
  inventory-lock-wait-time: 3000  # 재고 락 대기시간(ms)
  inventory-lock-lease-time: 5000 # 재고 락 유지시간(ms)
  max-order-per-user: 1          # 사용자당 최대 주문수
  order-timeout: 600000          # 주문 타임아웃(10분)

logging:
  level:
    com.jun.orderservice: DEBUG
    org.springframework.cloud.openfeign: DEBUG